services:
  nest-app:
    ports:
      - 3000:3000
    volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/letsencrypt/live/record-useful.kro.kr:/etc/letsencrypt/live/record-useful.kro/kr:ro
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER_NAME=${DB_USER_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PROD_PORT=${PROD_PORT}
      - DEV_PORT=${DEV_PORT}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - USER_EMAIL=${USER_EMAIL}
      - EMAIL_PASS=${EMAIL_PASS}

  nginx:
    volumes:
      - ./nginx/conf.d/production.conf:/etc/nginx/conf.d/server.conf:ro
